# mkdocs.yml
site_name : LIQENGINEBIN project
site_url: https://evnekdev.github.io/liqenginebin-docs/


extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  
nav:
  - Home :
  - Overview : index.md
  - Theoretical basis: theory.md
  